version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.133.21.78
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 10.133.21.78:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  json_producer:
    build:
      context: .
      dockerfile: JsonProducerDockerfile
    depends_on:
      - kafka
  consumer:
    build:
      context: .
      dockerfile: ConsumerDockerfile
    depends_on:
      - kafka
